require: []

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'examples/*.rb'

Layout/AlignHash:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false
